CREATE TABLE [dbo].[Enrollment] (
    [EnrollmentID]								   INT			  IDENTITY (253000, 1) NOT NULL,
	[ProjectEntryID]                               INT            NOT NULL,
    [PersonalID]                                   INT            NOT NULL,
    [ProjectID]                                    INT            NOT NULL,
    [EntryDate]                                    DATE           NOT NULL,
    [HouseholdID]                                  INT            NOT NULL,
    [RelationshipToHoH]                            INT            NOT NULL,
    [ResidencePrior]                               INT            NULL,
    [OtherResidencePrior]                          NVARCHAR (250) NULL,
    [ResidencePriorLengthOfStay]                   INT            NULL,
    [DisablingCondition]                           BIT            NULL,
    [EntryFromStreetESSH]                          BIT            NULL,
    [DateToStreetESSH]                             DATE           NULL,
    [TimesHomelessPastThreeYears]                  INT            NULL,
    [MonthsHomelessPastThreeYears]                 INT            NULL,
    [HousingStatus]                                INT            NULL,
    [DateOfEngagement]                             DATE           NULL,
    [InPermanentHousing]                           BIT            NULL,
    [ResidentialMoveInDate]                        DATE           NULL,
    [DateOfPATHStatus]                             DATE           NULL,
    [ClientEnrolledinPATH]                         BIT            NULL,
    [ReasonNotEnrolled]                            NVARCHAR (250) NULL,
    [WorstHousingSituation]                        NVARCHAR (250) NULL,
    [PercentAMI]                                   INT            NULL,
    [LastPermanentStreet]                          NVARCHAR (250) NULL,
    [LastPermanentCity]                            NVARCHAR (250) NULL,
    [LastPermanentState]                           NVARCHAR (50)  NULL,
    [LastPermanentZip]                             INT            NULL,
    [AddressDataQuality]                           INT            NULL,
    [DateOfBCPStatus]                              DATE           NULL,
    [FYSBYouth]                                    BIT            NULL,
    [ReasonNoServices]                             NVARCHAR (250) NULL,
    [SexualOrientation]                            NVARCHAR (50)  NULL,
    [FormerWardChildWelfare]                       BIT            NULL,
    [ChildWelfareYears]                            INT            NULL,
    [ChildWelfareMonths]                           INT            NULL,
    [FormerWardJuvenileJustice]                    NVARCHAR (250) NULL,
    [JuvenileJusticeYears]                         INT            NULL,
    [JuvenileJusticeMonths]                        INT            NULL,
    [HouseholdDynamics]                            NVARCHAR (50)  NULL,
    [SexualOrientationGenderIDYouth]               INT            NULL,
    [SexualOrientationGenderIDFam]                 INT            NULL,
    [HousingIssuesYouth]                           BIT            NULL,
    [HousingIssuesFam]                             BIT            NULL,
    [SchoolEducationalIssuesYouth]                 BIT            NULL,
    [SchoolEducationalIssuesFam]                   BIT            NULL,
    [UnemploymentYouth]                            BIT            NULL,
    [UnemploymentFam]                              BIT            NULL,
    [MentalHealthIssuesYouth]                      BIT            NULL,
    [MentalHealthIssuesFam]                        BIT            NULL,
    [HealthIssuesYouth]                            BIT            NULL,
    [HealthIssuesFam]                              BIT            NULL,
    [PhysicalDisabilityYouth]                      BIT            NULL,
    [PhysicalDisabilityFam]                        BIT            NULL,
    [MentalDisabilityYouth]                        BIT            NULL,
    [MentalDisabilityFam]                          BIT            NULL,
    [AbuseAndNeglectYouth]                         BIT            NULL,
    [AbuseAndNeglectFam]                           BIT            NULL,
    [AlcoholDrugAbuseYouth]                        BIT            NULL,
    [AlcoholDrugAbuseFam]                          BIT            NULL,
    [InsufficientIncome]                           BIT            NULL,
    [ActiveMilitaryParent]                         BIT            NULL,
    [IncarceratedParent]                           BIT            NULL,
    [IncarceratedParentStatus]                     INT            NULL,
    [ReferralSource]                               NVARCHAR (50)  NULL,
    [CountOutreachReferralApproaches]              INT            NULL,
    [ExchangeForSex]                               BIT            NULL,
    [ExchangeForSexPastThreeMonths]                BIT            NULL,
    [CountOfExchangeForSex]                        INT            NULL,
    [AskedOrForcedToExchangeForSex]                BIT            NULL,
    [AskedOrForcedToExchangeForSexPastThreeMonths] BIT            NULL,
    [WorkPlaceViolenceThreats]                     BIT            NULL,
    [WorkplacePromiseDifference]                   BIT            NULL,
    [CoercedToContinueWork]                        BIT            NULL,
    [LaborExploitPastThreeMonths]                  BIT            NULL,
    [HPScreeningScore]                             INT            NULL,
    [VAMCStation]                                  INT            NULL,
    [DateCreated]                                  DATE           NOT NULL,
    [DateUpdated]                                  DATE           NOT NULL,
    [UpdatedBy]                                    INT            NULL,
    [DateDeleted]                                  DATE           NULL,
	CONSTRAINT [PK_Enrollment] PRIMARY KEY CLUSTERED ([EnrollmentID] ASC),
    CONSTRAINT [FK_Enrollment_Client] FOREIGN KEY ([PersonalID]) REFERENCES [dbo].[Client] ([UUID])
);

