CREATE TABLE [dbo].[Exit] (
    [ExitID]                       INT           NOT NULL,
    [ProjectEntryID]               INT           NOT NULL,
    [PersonalID]                   INT           NOT NULL,
    [ExitDate]                     DATE          NOT NULL,
    [Destination]                  INT           NULL,
    [OtherDestination]             NVARCHAR (50) NULL,
    [AssessmentDisposition]        NVARCHAR (50) NULL,
    [OtherDisposition]             NVARCHAR (50) NULL,
    [HouseAssessment]              INT           NULL,
    [SubsidyInformation]           INT           NULL,
    [ConnectionWithSOAR]           BIT           NULL,
    [WrittenAftercarePlan]         BIT           NULL,
    [AssistanceMainstreamBenefits] BIT           NULL,
    [PermanentHousePlacement]      BIT           NULL,
    [TemporaryShelterPlacement]    BIT           NULL,
    [ExitCounseling]               BIT           NULL,
    [FurtherFollowUpServices]      BIT           NULL,
    [ScheduledFollowUpContacts]    BIT           NULL,
    [ResourcePackage]              BIT           NULL,
    [OtherAftercarePlanOrAction]   BIT           NULL,
    [ProjectCompletionStatus]      INT           NULL,
    [EarlyExitReason]              INT           NULL,
    [FamilyReunificationAchieved]  BIT           NULL,
    [DateCreated]                  DATE          NOT NULL,
    [DateUpdated]                  DATE          NOT NULL,
    [UpdatedBy]                    INT           NOT NULL,
    [DateDeleted]                  DATE          NULL,
    CONSTRAINT [PK_Exit] PRIMARY KEY CLUSTERED ([ExitID] ASC),
    CONSTRAINT [FK_Exit_Client] FOREIGN KEY ([PersonalID]) REFERENCES [dbo].[Client] ([UUID])
);

