CREATE TABLE [dbo].[IncomeBenefits] (
    [IncomeBenefitsID]            INT             NOT NULL,
    [ProjectEntryID]              INT             NOT NULL,
    [PersonalID]                  INT             NOT NULL,
    [InformationDate]             DATE            NOT NULL,
    [IncomeFromAnySource]         BIT             NULL,
    [TotalMonthlyIncome]          DECIMAL (16, 2) NULL,
    [Earned]                      BIT             NULL,
    [EarnedAmount]                DECIMAL (16, 2) NULL,
    [Unemployment]                BIT             NULL,
    [UnemploymentAmount]          DECIMAL (16, 2) NULL,
    [SSI]                         BIT             NULL,
    [SSIAmount]                   DECIMAL (16, 2) NULL,
    [SSDI]                        BIT             NULL,
    [SSDIAmount]                  DECIMAL (16, 2) NULL,
    [VADisabilityService]         BIT             NULL,
    [VADisabilityServiceAmount]   DECIMAL (16, 2) NULL,
    [VADisabilityNonService]      BIT             NULL,
    [VADisabilityNoServiceAmount] DECIMAL (16, 2) NULL,
    [PrivateDisability]           BIT             NULL,
    [PrivateDisabilityAmount]     DECIMAL (16, 2) NULL,
    [WorkersComp]                 BIT             NULL,
    [WorkersCompAmount]           DECIMAL (16, 2) NULL,
    [TANF]                        BIT             NULL,
    [TANFAmount]                  DECIMAL (16, 2) NULL,
    [GA]                          BIT             NULL,
    [GAAmount]                    DECIMAL (16, 2) NULL,
    [SocSecRetirement]            BIT             NULL,
    [SocSecRetirementAmount]      DECIMAL (16, 2) NULL,
    [Pension]                     BIT             NULL,
    [PensionAmount]               DECIMAL (16, 2) NULL,
    [ChildSupport]                BIT             NULL,
    [ChildSupportAmount]          DECIMAL (16, 2) NULL,
    [Alimony]                     BIT             NULL,
    [AlimonyAmount]               DECIMAL (16, 2) NULL,
    [OtherIncomeSource]           BIT             NULL,
    [OtherIncomeAmount]           DECIMAL (16, 2) NULL,
    [OtherIncomeSourceIdentify]   NVARCHAR (50)   NULL,
    [BenefitsFromAnySource]       BIT             NULL,
    [SNAP]                        BIT             NULL,
    [WIC]                         BIT             NULL,
    [TANFChildCare]               BIT             NULL,
    [TANFTransportation]          BIT             NULL,
    [OtherTANF]                   BIT             NULL,
    [RentalAssistanceOngoing]     BIT             NULL,
    [RentalAssistanceTemp]        BIT             NULL,
    [OtherBenefitsSource]         BIT             NULL,
    [OtherBenefitsSourceIdentify] NVARCHAR (50)   NULL,
    [InsuranceFromAnySource]      BIT             NULL,
    [Medicaid]                    BIT             NULL,
    [NoMedicaidReason]            NVARCHAR (50)   NULL,
    [Medicare]                    BIT             NULL,
    [NoMedicareReason]            NVARCHAR (50)   NULL,
    [SCHIP]                       BIT             NULL,
    [NoSCHIPReason]               NVARCHAR (50)   NULL,
    [VAMedicalServices]           BIT             NULL,
    [NoVAMedReason]               NVARCHAR (50)   NULL,
    [EmployerProvided]            BIT             NULL,
    [NoEmployerProvidedReason]    NVARCHAR (50)   NULL,
    [COBRA]                       INT             NULL,
    [NoCOBRAReason]               NVARCHAR (50)   NULL,
    [PrivatePay]                  BIT             NULL,
    [NoPrivatePayReason]          NVARCHAR (50)   NULL,
    [StateHealthIns]              BIT             NULL,
    [NoStateHealthInsReason]      NVARCHAR (50)   NULL,
    [HIVAIDSAssistance]           BIT             NULL,
    [HIVAIDSAssistanceReason]     NVARCHAR (50)   NULL,
    [ADAP]                        BIT             NULL,
    [NoADAPReason]                NVARCHAR (50)   NULL,
    [DataCollectionStage]         INT             NULL,
    [DateCreated]                 DATE            NULL,
    [DateUpdated]                 DATE            NULL,
    [UpdatedBy]                   INT             NULL,
    [DateDeleted]                 DATE            NULL,
    CONSTRAINT [PK_IncomeBenefits] PRIMARY KEY CLUSTERED ([IncomeBenefitsID] ASC),
    CONSTRAINT [FK_IncomeBenefits_Client] FOREIGN KEY ([PersonalID]) REFERENCES [dbo].[Client] ([UUID])
);

